### ISSUE TITLE
Add Maven in this project 

### ISSUE THREAD

**Issue by selvavaithi** [sayems/Cucumber#2]
It will be nice if you have begin with a maven to easy the cucumber installation process

**Comment by sayems** [comment]
Please explain how does maven make it any easier than gradle?

**Comment by selvavaithi** [comment]
Since this repository is for beginners to learn about cucumber it felt like maven is very basic to install so only said sayems.

**Comment by sayems** [comment]
I don't know what make you think maven is very basic to install over gradle? In fact, it's quite the opposite. Gradle make everything simple, and easy to use, managing dependencies is really easy. The build.gradle is very easy to read and self explanatory. 

If your using IntelliJ IDEA, you don't need to install gradle and configure anything. IntelliJ IDE automatically install gradle and configure everything for you. 

Please follow these step:
Step 0: Make sure JDK PATH environment variable is setup
Step 1: Clone the repository or Check out from Version Control within IntelliJ IDEA
Step 2: Open IntelliJ IDEA and select Import Project
Step 3: Select Import project from external model
Step 4: Finish (It will automatically install gradle and configure maven dependencies for you)
Step 5: Run Cucumber test!

**Comment by sayems** [comment]
Let us know if anything doesn't work, I'm going to close out this issue for now :-)

**Comment by selvavaithi** [comment]
sure Sayems.. Thanks
